### ISSUE TITLE
Training Voice Wake-up Model on iOS System

### ISSUE THREAD

**Issue by Milker90** [dscripka/openWakeWord#136]
Hi @dscripka, This is an amazing project, really impressive! It saves me a lot of time in training a voice wake-up model, which is very helpful for me.

Now I want to use it to train a voice wake-up model and then run the model on iOS system. I'm using the C++ version provided by @synesthesiam, but I feel the performance is not very good. I have a few questions that I would like some help with:

1. Why is it that when we train, the length of positive sample audio is quite long, for example, the positive sample time is 1 second, but during input, only 80ms or (4*80ms) is needed to recognize the keyword?
2. The detection performance is poor when there is significant background noise.
3. I run detect_from_microphone.py and play the automatically generated training positive samples, but some audio samples are never detected.

Thank you very much.

**Comment by sanjuktasr** [comment]
Hi I am not getting good accuracy while training. Can you please give me an idea how you have configured the model while training @Milker90.

**Comment by Milker90** [comment]
I generated about 15,000 samples, added some samples of local people speaking English, added some negative samples of local people speaking, and then changed dnn to rnn

Since the proportion of local English-speaking samples during training is relatively low, the recognition rate feels a bit low. I don't have an English environment, so I'm not sure how high the misrecognition rate is. I still need to test it. The test program I wrote seems to be okay.

In addition, some adjustments have been made to the C++ code to make the flow recognition process easier to identify keywords.

But there is still a big problem that the CPU usage is relatively high, reaching 37%-40%. I want to use core ml to achieve it, but I don’t have an idea yet.

**Comment by sanjuktasr** [comment]
ok how much accuracy ,recall, false positive did you get?

**Comment by dscripka** [comment]
> Hi @dscripka, This is an amazing project, really impressive! It saves me a lot of time in training a voice wake-up model, which is very helpful for me.
> 
> Now I want to use it to train a voice wake-up model and then run the model on iOS system. I'm using the C++ version provided by @synesthesiam, but I feel the performance is not very good. I have a few questions that I would like some help with:
> 
>     1. Why is it that when we train, the length of positive sample audio is quite long, for example, the positive sample time is 1 second, but during input, only 80ms or (4*80ms) is needed to recognize the keyword?
> 
>     2. The detection performance is poor when there is significant background noise.
> 
>     3. I run detect_from_microphone.py and play the automatically generated training positive samples, but some audio samples are never detected.
> 
> 
> Thank you very much.

Thank you for the comment @Milker90, I'm glad you are finding the library useful! As to your questions:

1) During training, the models operates on input features that correspond to 1-2 second audio clip duration. This is the same during real-time usage, but since a 1-2 second latency on detection is very slow for wakeword applications instead the code predicts on the 1-2 second windows every 80 ms by default. The code internally builds of buffers of audio and input features so that every 80 ms new data is added for the next prediction.

2) Yes, this is a challenge with all wakeword models that can't rely on special hardware to help separate background noise. This can be reduced in some cases by training custom models that are more robust to particular types of background noise, but the process is not simple.

3) It's hard to tell what might be happening without more information, but even well performing models to not have 100% recall on the training data, so some missed samples are expected. However, if the performance with the `detect_from_microphone.py` scripts is substantially lower than expected for a custom model, you may need to experiment with other model training parameters to help increase performance.

As for C++ performance, the implementation by @synesthesiam is likely the best reference. It may not be optimized fully, however, and I agree that getting the best performance on iOS would likely require re-implementing the entire inference process in CoreML.
