### ISSUE TITLE
Wakeword detection is looping...

### ISSUE THREAD

**Issue by goldyfruit** [dscripka/openWakeWord#157]
Hi there,

I'm really not sure why but for some reason, when a wakeword is detected _(tried Alexa, Hey Mycroft and Hey Jarvis)_, the wakeword detection keeps looping very randomly.

I don't have any special noise around. Here are two videos:

https://github.com/dscripka/openWakeWord/assets/614115/da4cadcf-1a78-4425-939c-af21a9ca7cd7

https://github.com/dscripka/openWakeWord/assets/614115/37659ea2-0275-4fd5-a688-6abbfebb2539

**Comment by dscripka** [comment]
Are you using openWakeWord in OVOS, by chance (since it looks like you are using Mycroft hardware)? If so, are you using [this plugin](https://github.com/OpenVoiceOS/ovos-ww-plugin-openWakeWord)? There is some logic in this plugin to clear out buffers and avoid looping detection like this, but perhaps something isn't working.

If you aren't using the plugin in OVOS, and instead are using custom code, you'll need to either continue feeding in audio after the activation (the recommended approach) and just ignore any detections until you are ready to accept them again, or [manually clear the audio buffers](https://github.com/dscripka/openWakeWord/blob/c40fe924ffa12e9ddf24a3e5fcdeb4fd58ab07eb/openwakeword/model.py#L226).

**Comment by goldyfruit** [comment]
@dscripka Yes I'm using a Mark II device with OVOS and the plugin your linked.

**Comment by dscripka** [comment]
The plugin currently has the buffer clearing functionality [in place](https://github.com/OpenVoiceOS/ovos-ww-plugin-openWakeWord/blob/b6571626eab41cc4219493d058743355c0872c5b/ovos_ww_plugin_openwakeword/__init__.py#L68), so it should work.

And I do try and track that plugin and make sure it works with correctly with openWakeWord; not sure why it isn't working now. Are you perhaps running a newer version of OVOS?

**Comment by goldyfruit** [comment]
> And I do try and track that plugin and make sure it works with correctly with openWakeWord; not sure why it isn't working now. Are you perhaps running a newer version of OVOS?

I'm using the `dev` branch https://github.com/OpenVoiceOS/ovos-dinkum-listener

**Comment by goldyfruit** [comment]
@dscripka I will let the `ovos-installer` keep installing the `ovos-ww-plugin-openWakeWord` plugin but will not enable it by default _(which was my initial plan)_, this will be a user decision.

I will close the issue for now, feel free to re-open it if you want me to run some tests. :+1:
