### ISSUE TITLE
Error during the training step

### ISSUE THREAD

**Issue by michaeldufour** [dscripka/openWakeWord#217]
I have this error during the training step 

TypeError                                 Traceback (most recent call last)
<ipython-input-8-c802ee0a7557> in <cell line: 93>()

Does anyone know why?

**Comment by justahuman33** [comment]
I am getting same error. Please see below

RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-4-c802ee0a7557>](https://localhost:8080/#) in <cell line: 93>()
     91     return None
     92 
---> 93 convert_onnx_to_tflite(f"my_custom_model/{config['model_name']}.onnx", f"my_custom_model/{config['model_name']}.tflite")
     94 
     95 # Automatically download the trained model files

11 frames

[/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py](https://localhost:8080/#) in __new__(cls, name, full_name, index, number, type, cpp_type, label, default_value, message_type, enum_type, containing_type, is_extension, extension_scope, options, serialized_options, has_default_value, containing_oneof, json_name, file, create_key)
    551                 has_default_value=True, containing_oneof=None, json_name=None,
    552                 file=None, create_key=None):  # pylint: disable=redefined-builtin
--> 553       _message.Message._CheckCalledFromGeneratedFile()
    554       if is_extension:
    555         return _message.default_pool.FindExtensionByName(full_name)

TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by justahuman33** [comment]
locate the pip install command in Step 2:
!pip install tensorflow-cpu==2.8.1
modify to:
!pip install tensorflow-cpu==2.8.1
!pip install protobuf==3.20.3

**Comment by dscripka** [comment]
The public notebook has been updated to incorporate this fix. Thanks @justahuman33!

**Comment by michaeldufour** [comment]
Thanks for your helps @dscripka
