### ISSUE TITLE
"Input overflowed" Exception when Running "detect_from_microphone.py"

### ISSUE THREAD

**Issue by ab-tools** [dscripka/openWakeWord#36]
Hello @dscripka,

trying to run your `detect_from_microphone.py` example script as it is, but I always do get following exception:
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.



            Model Name         | Score | Wakeword Status############################################
            --------------------------------------
            alexa              | 0.000 | --                    #####################################
            hey_mycroft        | 0.000 | --
            hey_jarvis         | 0.000 | --
            1_minute_timer     | 0.000 | --
            5_minute_timer     | 0.000 | --
            10_minute_timer    | 0.000 | --
            20_minute_timer    | 0.000 | --
            30_minute_timer    | 0.000 | --
            1_hour_timer       | 0.000 | --
            weather            | 0.000 | --
Traceback (most recent call last):
  File "/home/mic/openWakeWord/detect_from_microphone.py", line 74, in <module>
    audio = np.frombuffer(mic_stream.read(CHUNK), dtype=np.int16)
  File "/home/mic/openWakeWord/.env/lib/python3.9/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
OSError: [Errno -9981] Input overflowed
```

I verified by writing the microphone stream to a WAV file that the input device used is correct. So recording with PyAudio works fine in general.

The interesting thing is that the "Input overflowed" exception only happens if the `Model` class is instantiated.

If I reduce the script to just this here it still happens:
```
# Get microphone stream
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 16000
CHUNK = args.chunk_size
audio = pyaudio.PyAudio()
mic_stream = audio.open(format=FORMAT, channels=CHANNELS, rate=RATE, input=True, frames_per_buffer=CHUNK)

# Load pre-trained openwakeword models
if args.model_path != "":
    owwModel = Model(wakeword_models=[args.model_path], inference_framework=args.inference_framework)
else:
    owwModel = Model(inference_framework=args.inference_framework)

n_models = len(owwModel.models.keys())

# Run capture loop continuosly, checking for wakewords
if __name__ == "__main__":
    # Generate output string header
    print("\n\n")
    print("#"*100)
    print("Listening for wakewords...")
    print("#"*100)
    print("\n"*(n_models*3))

    while True:
        # Get audio
        audio = np.frombuffer(mic_stream.read(CHUNK), dtype=np.int16)
        continue # do nothing with audio received
```

If I now also remove the `Model` initialization I do not get this exception anymore:
```
# Get microphone stream
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 16000
CHUNK = args.chunk_size
audio = pyaudio.PyAudio()
mic_stream = audio.open(format=FORMAT, channels=CHANNELS, rate=RATE, input=True, frames_per_buffer=CHUNK)

# Run capture loop continuosly, checking for wakewords
if __name__ == "__main__":
    # Generate output string header
    print("\n\n")
    print("#"*100)
    print("Listening for wakewords...")
    print("#"*100)

    while True:
        # Get audio
        audio = np.frombuffer(mic_stream.read(CHUNK), dtype=np.int16)
        continue # do nothing with audio received
```

This also happens when I provide one specific model as argument, by the way.

Do you have any idea why the `Model` class initialization leads to this "Input overflowed" exception when reading the next audio chunk?
To be precise, I found out that it can read the first chunk, the exception happens when `mic_stream.read(CHUNK)` is called the second time.

Any idea on this would be much appreciated!

Thanks a lot for your efforts again
Andreas

P. S.: I guess the `--chunk_size` argument which also has a default value is not meant to be set as `required=True`. You might want to fix that in the example.

**Comment by dscripka** [comment]
This is indeed very strange behavior, @ab-tools. I haven't noticed issues with buffer overflows in PyAudio on the platforms that I've tested thus far (x86, RPi3 and RPi4). Typically this happens when the computation done between blocking reads from PyAudio is taking too long, but as you've reproduced the issue even when the openWakeWord prediction step is disabled that shouldn't be the issue. Unfortunately I don't (yet) have a RPi Zero 2W, so I can't reproduce on the same hardware.

Setting `exception_on_overflow` to False is a viable workaround, but can lead to decreased performance if too many audio samples are being lost. Do you notice any significant change in performance with this enabled? You could also try using try/except blocks to determine if the buffer overflow happens on every single read, or just intermittently when the script is first started.

Finally, you could try configuring PyAudio to read from the microphone in [non-blocking mode](https://gist.github.com/KenoLeon/13dfb803a21a08cf224b2e6df0feed80) and see if that avoids the issue as well.
